name: Run publish @totvs/po-theme

env:
  WORKING_DIR: /home/runner/work/po-theme-totvs/po-theme-totvs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out po-theme-totvs
      uses: actions/checkout@v4

    - run: npm install -g @po-ui/theme-cli
    - run: npm install
    - run: npm run build

    - name: Get package.json version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    # PUBLISH NPM PO-THEME-TOTVS
    - name: po-theme-totvs - publish
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish ${{env.WORKING_DIR}}/dist --access=public
      env:
        PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: po-theme-totvs - add "latest" tag
      run: npm dist-tags add @totvs/po-theme@${{ env.PACKAGE_VERSION }}
      working-directory: ${{env.WORKING_DIR}}
      env:
        PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
